# Generated by Django 2.0.1 on 2018-01-12 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('messageText', models.CharField(max_length=500)),
                ('creatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagecreator_user_set', to=settings.AUTH_USER_MODEL)),
                ('recipientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagerecipient_user_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('archived', models.BooleanField()),
                ('creatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threadcreator_user_set', to=settings.AUTH_USER_MODEL)),
                ('recipientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threadrecipient_user_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Thread'),
        ),
    ]
